### PR TITLE
added user-defined ack-deadline

### PR DESCRIPTION
**Pull request by josephlewis42**

### CODE REVIEW

**Comment by amrmotan** [comment]
@josephlewis42 Thanks for working on that.
I will reply back once I test it.

**Comment by colinsurprenant** [comment]
LGTM but not tested locally, did you complete your tests @amrmotan ? I'll go ahead and approve the review but would prefer we wait for @amrmotan feedback before merging.

**Comment by amrmotan** [comment]
@colinsurprenant Sorry not yet. Hopefully, I will get the time to test it before the end of today.
I'll keep you posted.

**Comment by josephlewis42** [comment]
@amrmotan have you had a chance to test this out yet?

**Comment by mad-it** [comment]
Any updates on this? I am currently facing some minor issues where this would alleviate the problem.

**Pull request closed without merging**
