### PR TITLE
Issue #34 Fix - Rollback Guava to v19

### PR DESCRIPTION
**Pull request by SebScoFr**
This fix was originally proposed by @tacomafour on #35, credits go to him.
Unfortunately it seems he didn't get a chance to do a PR for it so here it is. I'm keen to see that merged rapidly so people can benefit from it :)

### CODE REVIEW

**Comment by SebScoFr** [comment]
@josephlewis42 Master still seems to be failing in Travis though

**Comment by josephlewis42** [comment]
@SebScoFr I think that error is due to one of the other dependencies conflicting with guava 19.0. I can try to dig in to see if we can roll that back to an earlier version that's compatible with it.

**Comment by SebScoFr** [comment]
That's be awesome

**Comment by SebScoFr** [comment]
Interesting. Can you reproduce the error on your side?
```
[ERROR][org.logstash.Logstash] java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;J)V
```

**Comment by SvenW** [comment]
@SebScoFr unfortunately I´m running v6.1.0 of logstash right now and I can´t switch to a newer version at the moment so therefore it´s hard for me to reproduce.

**Comment by SebScoFr** [comment]
@SvenW ok, let us know if you get a chance :)

**Comment by josephlewis42** [comment]
@SebScoFr It looks like Logstash reverted their guava version between 6.2.3 to 6.2.4. Here's the commit that I think did it: https://github.com/elastic/logstash/commit/a425a422e03087ac34ad6949f7c95ec6d27faf14

The [1.1 version imports guava 19](https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format/1.1) and the [1.5 version imports Guava 22](https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format/1.5).

``` sh
user@elasticstack:~$ docker run -it docker.elastic.co/logstash/logstash:6.2.3 bash
WARNING: IPv4 forwarding is disabled. Networking will not work.
bash-4.2$ find . | grep guava
./logstash-core/lib/jars/guava-22.0.jar
bash-4.2$ 
```

``` sh
user@elasticstack:~$ docker run -it docker.elastic.co/logstash/logstash:6.2.4 bash
WARNING: IPv4 forwarding is disabled. Networking will not work.
bash-4.2$ find . | grep guava
./logstash-core/lib/jars/guava-19.0.jar
bash-4.2$
```

**Comment by josephlewis42** [comment]
@SebScoFr I think there's one more option, if you use Logstash 6.2.3 rather than 6.2.4. It's not ideal, but if you need some of the new features of the 1.2.0 plugin it might be the way to go.

I created a ticket you can watch in the main Logstash repository to see if there's a fix: https://github.com/elastic/logstash/issues/9592 It's likely this issue will start to affect the other Google plugins as well so I hope we can get it resolved.

**Comment by SebScoFr** [comment]
Ok it’s not ideal but that’s indeed a way to workaround it. I’ll give it a try.

**Comment by josephlewis42** [comment]
Hey all, this was fixed upstream, but unfortunately it won't make it in time for 6.3.0, so it'll be fixed in 6.3.1.

More here: https://github.com/elastic/logstash/pull/9622

@SebScoFr thank you so much for your patch, even if it looks like this will be fixed without it your work with debugging got this whole thing moving.

**Comment by SebScoFr** [comment]
Thanks for the update @josephlewis42.
Closing this now.

**Comment by andyshinn** [comment]
For those still waiting for the upstream fix, it doesn't appear to have made it in to 6.3.1. I've still got the problem with Logstash 6.3.1 and logstash-input-google_pubsub 1.2.0.

**Comment by BenjaminLSmith** [comment]
I am also running Logstash 6.3.1 and getting the same Error:
`[2018-07-27T18:40:41,447][ERROR][org.logstash.Logstash    ] java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;J)V`

Looks like the fix missed the 6.3.1 release but made it into 6.3.2: https://github.com/elastic/logstash/pull/9836
https://www.elastic.co/guide/en/logstash/current/logstash-6-3-2.html

**Pull request closed without merging**
