### PR TITLE
Update JARs to work with Logstash Output Google Pubsub

### PR DESCRIPTION
**Pull request by josephlewis42**
When used in conjunction with `logstash-input-google_pubsub` this plugin was experiencing an issue causing crashes because the JARs the two depended on were different: https://github.com/logstash-plugins/logstash-output-google_pubsub/issues/7

This PR updates this plugin to use the same set of JARs as the other one (which are now out of beta and stable)

### CODE REVIEW

**Comment by josephlewis42** [comment]
Hi @robbavey, thanks for reviewing this so quickly. GitHub isn't showing me your comment inline, would you mind duplicating it in the comments here?

I think this might be a better comment because it provides a better background on the issue if you'd give me your take on it:

```
- Use the same Pub/Sub client library as [`logstash-output-google_pubsub`](https://github.com/logstash-plugins/logstash-output-google_pubsub) so you can use both plugins without the dependencies conflicting
```

**Comment by robbavey** [comment]
Not quite sure what happened there, @josephlewis42, but my nit was an ask to have the changelog entry [formatted according to the guidelines in the Logstash contributors guide](https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md#logstash-plugin-changelog-guidelines)

**Comment by josephlewis42** [comment]
I can merge/tag/build a gemfile to release on GitHub, but don't have access to the rubygem. Would you be able to push it out there or `gem owner --add graphite-elastic-gems@google.com logstash-input-google_pubsub` so I can?

Thanks!

**Comment by robbavey** [comment]
@josephlewis42 If you can merge this in, I can take care of publishing it. I don't think I have the rights to add you to the owner's list, so I will cc @acchen97 who should be able to.

**Comment by josephlewis42** [comment]
Awesome, thanks! I've got it merged in and tagged.

**Comment by robbavey** [comment]
@josephlewis42 The gem is[ up](https://rubygems.org/gems/logstash-input-google_pubsub/versions/1.2.1). Thanks!

**Pull request merged**
