### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by erjohnso**
Hi @suyograo,

Sorry for the delay and thanks for creating the repo. Here's the initial PR to add a new input plugin for Google PubSub.

I'm eager to help resolve any issues you find with the plugin.

Cheers, Eric

### CODE REVIEW

**Comment by erjohnso** [comment]
Hello @suyograo - anything else you need from me to help with the review / merge?

**Comment by erjohnso** [comment]
Hello @suyograo - anything else you need from me to help with the review / merge?

**Comment by ahmerbasit** [comment]
Hi @suyograo, do we have an ETA on when this might get reviewed/submitted/merged?

**Comment by ahmerbasit** [comment]
Any update?

**Comment by ahmerbasit** [comment]
I am struggling to find out what's the next step here. There is virtually no response from suygrao@ in over a month.

**Comment by acchen97** [comment]
Thanks for being patient with us. The team is currently heads down crunching out the next minor release right now, we'll circle back sometime after that.

Appreciate the interest and the PR @erjohnso

**Comment by moeadham** [comment]
So, is anybody going to merge this?

**Comment by acchen97** [comment]
@erjohnso thanks for your contribution, its an excellent addition to the ecosystem. I'll be reaching out to you directly regarding continued maintenance of this plugin.

**Comment by erjohnso** [comment]
sg, thanks @acchen97 and @suyograo!

**Pull request merged**
